// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Perlishnov/gotrainingproject/internal/config"
	"github.com/Perlishnov/gotrainingproject/internal/controller"
	"github.com/Perlishnov/gotrainingproject/internal/dao"
	"github.com/Perlishnov/gotrainingproject/internal/middleware"
	"github.com/Perlishnov/gotrainingproject/internal/service"
	"github.com/Perlishnov/gotrainingproject/internal/utils"
	"github.com/Perlishnov/gotrainingproject/pkg/database"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	dbConfig := provideDBConfig(configConfig)
	logger := provideLogger(configConfig)
	db, err := database.NewMySQLConnection(dbConfig, logger)
	if err != nil {
		return nil, err
	}
	userDAO := dao.NewUserDAO(db)
	userService := service.NewUserService(userDAO, logger)
	userController := controller.NewUserController(userService, logger)
	jwtUtil := utils.NewJWTUtil(configConfig)
	authService := service.NewAuthService(userDAO, jwtUtil, logger)
	authController := controller.NewAuthController(authService, logger)
	authMiddleware := middleware.NewAuthMiddleware(jwtUtil, logger)
	app := NewApp(userController, authController, authMiddleware, logger)
	return app, nil
}

// wire.go:

// provideLogger creates a logger using the log level from config.
func provideLogger(cfg *config.Config) *logrus.Logger {
	return utils.NewLogger(cfg.LogLevel)
}

// provideDBConfig creates database.DBConfig from config (needed for MySQL only).
func provideDBConfig(cfg *config.Config) database.DBConfig {
	return database.DBConfig{
		User:     cfg.DBUser,
		Password: cfg.DBPassword,
		Host:     cfg.DBHost,
		Port:     cfg.DBPort,
		DBName:   cfg.DBName,
	}
}

type App struct {
	UserController *controller.UserController
	AuthController *controller.AuthController
	AuthMiddleware *middleware.AuthMiddleware
	Logger         *logrus.Logger
}

func NewApp(
	userCtrl *controller.UserController,
	authCtrl *controller.AuthController,
	authMW *middleware.AuthMiddleware,
	logger *logrus.Logger,
) *App {
	return &App{
		UserController: userCtrl,
		AuthController: authCtrl,
		AuthMiddleware: authMW,
		Logger:         logger,
	}
}
